version: '3.9'
services:
  backend:
    container_name: avito-backend
    build:
      context: .
      dockerfile: ./deploy/service/Dockerfile
    ports:
      - '8000:8080'
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - avito-network

  db:
    container_name: pg_database
    build:
      context: .
      dockerfile: ./deploy/pg/Dockerfile
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-data-test:/var/lib/postgresql/test
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - avito-network
  
  test:
    container_name: integration-tests
    build:
      context: .
      dockerfile: ./deploy/tests/Dockerfile
    environment:
      - RUN_TESTS=${RUN_TESTS}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - avito-network

volumes:
  db-data:
    driver: local
  db-data-test:
    driver: local


networks:
  avito-network:
    external: true